fieldLayouts:
  0da92eac-6399-4241-ac14-4382190845e8:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: __blank__
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 63bc3fb9-7e4a-44e1-abf8-b4a8eda1fd8c # Logos
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 759acc15-f189-482d-af8b-3b8eb87ddd66 # Correct Logo Usage
            instructions: ''
            label: 'Correct Logo Usage'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 83f2c17a-02dc-452e-8f88-9a24d342fa4e # Incorrect Logo Usage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Logos
        sortOrder: 1
handle: brandGuidelines
hasTitleField: false
name: 'Brand Guidelines'
section: 0b3df78b-ac88-4bf8-a16e-052c4983f968 # Brand Guidelines
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
