fieldLayouts:
  8a32679e-d611-4e06-a586-0bfd7a3bcb03:
    tabs:
      -
        elements:
          -
            fieldUid: e21f420c-3fc2-4ddc-afdc-b4ae78c526e3 # Author
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6d529a0f-713a-4b29-b07b-1172eff1cd0e # Featured Image
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: ''
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 611a4f85-a52f-4a80-8c72-a08f043b4268 # Summary
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f2cf9586-f81f-404f-b8e6-57b9fe1d530d # Post Categories
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0a9bf03d-0f29-4dd6-83c6-03d236e25e91 # Post Content
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: news
hasTitleField: true
name: News
section: 0bddbef9-ed48-48d3-8400-ae8d91152a64 # News
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
