fieldLayouts:
  0bcb391d-08f0-4518-a1ef-06a7c4945dea:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 9413c31d-3095-4413-a3a9-7aab05f22886 # Community Rules
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Community Rules'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 917f5627-3dc6-423b-aa1d-d3e9d2553add # Member Rules
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Member Rules'
        sortOrder: 2
handle: phoenixRules
hasTitleField: false
name: Rules
section: e8cf3d59-dc7d-4d37-9c21-e03049533db0 # Rules
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
