defaultPlacement: end
fieldLayouts:
  7596a22c-ea42-48c8-875f-beb02f2cc35c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 4cce5b3f-ef9a-4e49-91bc-9bb461e25220 # Relations
            instructions: ''
            label: 'Used in'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: newsCategories
name: 'News Categories'
siteSettings:
  0a9ef065-97f8-4583-b4a1-5a8e4d790203: # Phoenix
    hasUrls: true
    template: news/_category
    uriFormat: 'news/category/{slug}'
structure:
  maxLevels: 1
  uid: 7c8835d9-956d-4a18-8596-d3e5113cffec
