defaultPlacement: end
fieldLayouts:
  f7a92616-a221-4863-8a8d-c89c323a733d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: c8389542-b6fa-4246-b78a-2fc2e1264ece # About
            instructions: 'A short, one/two sentence description that describes what the position does'
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4cce5b3f-ef9a-4e49-91bc-9bb461e25220
            instructions: ''
            label: 'Members with position'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: teamPositions
name: 'Team Positions'
siteSettings:
  0a9ef065-97f8-4583-b4a1-5a8e4d790203: # Phoenix
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 774c77b6-451c-49ab-ac3b-07a3710c769b
