columnSuffix: null
contentColumnType: string
fieldGroup: 9c6a2d68-bb02-44d9-8d54-d315b160f045 # Brand Guidelines
handle: brandColours
instructions: ''
name: 'Brand Colours'
searchable: false
settings:
  contentTable: '{{%matrixcontent_brandcolours}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
