columnSuffix: null
contentColumnType: string
fieldGroup: 68d83b64-a88b-4296-891d-5292a362e035 # Careers
handle: careerApplicationForm
instructions: ''
name: 'Application Form'
searchable: false
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: verbb\formie\fields\Forms
