columnSuffix: flptolwe
contentColumnType: text
fieldGroup: e50e2ae1-1c46-4cc3-922a-8b9568186243 # Legal
handle: communityRules
instructions: ''
name: 'Community Rules'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes:
    - de587533-76d9-4747-a138-71e89ccee6f5 # Site
  cleanupHtml: true
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
