columnSuffix: null
contentColumnType: string
fieldGroup: 9c6a2d68-bb02-44d9-8d54-d315b160f045 # Brand Guidelines
handle: correctLogos
instructions: 'Examples of **correct** logo usage'
name: 'Correct Logo Usage'
searchable: false
settings:
  contentTable: '{{%matrixcontent_correctlogos}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
