columnSuffix: kqamhhiu
contentColumnType: datetime
fieldGroup: 6a47a1ab-b90e-44c5-85bd-7cd2418f1474 # Timeline Fields
handle: date
instructions: ''
name: Date
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: '30'
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
