columnSuffix: null
contentColumnType: string
fieldGroup: 6b9b8791-54fd-4a11-acb5-43f1692e6f6b # Partner Fields
handle: logo
instructions: ''
name: Logo
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:707026a3-1953-4b64-a6fb-f842bdfafde7' # News
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:707026a3-1953-4b64-a6fb-f842bdfafde7' # News
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:dc6e9949-7832-497f-8453-c4982c626a9c' # Partners
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
