columnSuffix: null
contentColumnType: string
fieldGroup: d81fe9c4-26c1-4f72-8c78-89894a2ae2f4 # Post Fields
handle: postCategories
instructions: ''
name: 'Post Categories'
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: 'group:5eaf4579-5ea7-41fd-9ea5-20cfcef34af0' # News Categories
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
