columnSuffix: null
contentColumnType: string
fieldGroup: 7386afed-ad3a-4215-9779-22c0947e4b3e # Team Member Fields
handle: profilePicture
instructions: ''
name: 'Profile Picture'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:8ed20a17-9666-4d48-acbb-87e39d5f2831' # Team
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: thumbs
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:707026a3-1953-4b64-a6fb-f842bdfafde7' # News
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:8ed20a17-9666-4d48-acbb-87e39d5f2831' # Team
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
