columnSuffix: gcuhlhkk
contentColumnType: string
fieldGroup: 38bc5335-6961-4b32-b011-c2925eb5486f # Common
handle: relations
instructions: ''
name: Relations
searchable: false
translationKeyFormat: null
translationMethod: site
type: internetztube\elementRelations\fields\ElementRelationsField
