columnSuffix: null
contentColumnType: string
fieldGroup: 38bc5335-6961-4b32-b011-c2925eb5486f # Common
handle: requirements
instructions: ''
name: Requirements
searchable: false
settings:
  contentTable: '{{%matrixcontent_requirements}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
