columnSuffix: clsajpiz
contentColumnType: text
fieldGroup: d81fe9c4-26c1-4f72-8c78-89894a2ae2f4 # Post Fields
handle: summary
instructions: 'Enter a brief, one or two sentence post summary.'
name: Summary
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '1'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
