columnSuffix: wpppuney
contentColumnType: text
fieldGroup: 121970e2-9425-45cd-a8f1-7f026e67839e # Socials
handle: truckersmpId
instructions: 'Only the ID, **not** the URL.'
name: 'TruckersMP ID'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
