columnSuffix: rohdqcvw
contentColumnType: text
fieldGroup: dcd87449-f024-484e-b16d-21f3a078647e # Company Socials
handle: truckersmpVtcId
instructions: 'Only the ID or slug, **not** the URL.'
name: 'TruckersMP VTC ID'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
