columnSuffix: dgryowwb
contentColumnType: text
fieldGroup: 7386afed-ad3a-4215-9779-22c0947e4b3e # Team Member Fields
handle: twitchUsername
instructions: 'Only the username, **not** the URL.'
name: 'Twitch Username'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
