dateModified: 1642101751
email:
  fromEmail: $MAIL_FROM_ADDRESS
  fromName: $MAIL_FROM_NAME
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: $MAIL_ENCRYPTION
    host: $MAIL_HOST
    password: $MAIL_PASSWORD
    port: $MAIL_PORT
    timeout: '10'
    useAuthentication: '1'
    username: $MAIL_USERNAME
  transportType: craft\mail\transportadapters\Smtp
meta:
  __names__:
    0a9bf03d-0f29-4dd6-83c6-03d236e25e91: 'Post Content' # Post Content
    0a9ef065-97f8-4583-b4a1-5a8e4d790203: Phoenix # Phoenix
    0a8951d8-3817-4ac4-8ec2-57051f00238a: 'Our Fleet' # Our Fleet
    0b3df78b-ac88-4bf8-a16e-052c4983f968: 'Brand Guidelines' # Brand Guidelines
    0bddbef9-ed48-48d3-8400-ae8d91152a64: News # News
    0ed9685f-56ae-4d50-b010-18db58c0c4f5: Completed # Completed
    1b03c006-2839-4652-b534-5f6e6640bb1f: Item # Item
    1b8d609a-4d46-4b14-a53e-b08fd8c89e5a: News # News
    1d3d2f8a-80e9-4f2f-ad50-69e13aa8d67f: Question # Question
    1e13d2f1-5244-411c-b082-a7ed076b9317: Text # Text
    1ee3f36f-8538-47a1-8ed5-6f0e6986693f: 'FAQ Items' # FAQ Items
    2c8cdca8-a909-4cc0-8aaf-bab454f00013: 'Recruitment FAQ' # Recruitment FAQ
    2c156369-c025-4b90-86b7-878137ad5113: Requirements # Requirements
    3e5b7079-f29c-42b8-8234-f7d8ce164ce6: Example # Example
    4c882c79-0491-44ed-8f8f-73419177aad3: Home # Home
    4cce5b3f-ef9a-4e49-91bc-9bb461e25220: Relations # Relations
    4e5fac71-6919-4b9b-a0e6-96fd59b4bd16: 'Public Schema' # Public Schema
    5b3a42e5-ec56-4dab-8b94-d0a45f61734c: 'Profile Picture' # Profile Picture
    5e19c644-0362-4afe-9fc4-45cc5f32ee43: Description # Description
    5ea22a6f-7c9e-481a-9d5b-082865124bf6: Colour # Colour
    5eaf4579-5ea7-41fd-9ea5-20cfcef34af0: 'News Categories' # News Categories
    6ac6b856-c4bb-47c0-9d8a-749cbe20f95e: Requirement # Requirement
    6b9b8791-54fd-4a11-acb5-43f1692e6f6b: 'Partner Fields' # Partner Fields
    6bccb7b8-eeac-42b5-981c-cc567a1d2314: 'Discord Invite' # Discord Invite
    6d529a0f-713a-4b29-b07b-1172eff1cd0e: 'Featured Image' # Featured Image
    7a444e6c-effe-4031-a9b7-f24f92b4ef2b: Contact # Contact
    7c8ec1a0-39aa-4d3e-96bf-2aa905289ffa: 'Example Description' # Example Description
    8b8f7d8a-ced8-41b7-8132-2ff407ac591c: 'News Index' # News Index
    8ed20a17-9666-4d48-acbb-87e39d5f2831: Team # Team
    9a2d8217-0087-49b4-b760-b4dad07a1c57: 'About Us' # About Us
    9c6a2d68-bb02-44d9-8d54-d315b160f045: 'Brand Guidelines' # Brand Guidelines
    9d57e550-7644-47f6-a197-47ddaa230d1f: Home # Home
    9e4e2aa5-2938-472c-9ef6-c2d3d67203a1: Answer # Answer
    11f1310a-4e06-4290-8371-2a05672b9151: 'About Us' # About Us
    15ea378a-5d78-40c9-9f13-caec26f279e1: 'Privacy Policy' # Privacy Policy
    18e13e63-45a0-48c2-a5ae-2dfb7c27424f: Logo # Logo
    25ed42ae-bd38-4a53-a160-9fca36906d1f: 'Facebook Username' # Facebook Username
    27c27297-3638-454a-92b0-4fbf0313ef85: 'Cookie Policy' # Cookie Policy
    34c5216f-50a5-4dac-ab17-844b6ad4ac26: New # New
    38bc5335-6961-4b32-b011-c2925eb5486f: Common # Common
    56fd09ac-063c-4650-b977-ad67708341c6: 'Our DriversHub' # Our DriversHub
    63bc3fb9-7e4a-44e1-abf8-b4a8eda1fd8c: Logos # Logos
    67db21f0-d180-441b-b8ca-aa6a11c9b00e: Examples # Examples
    79a4a62f-a360-4b4b-acf3-4c2a7028f9cb: Text # Text
    79b7c25d-1c23-4710-9989-91bd5bfee85a: 'Team Index' # Team Index
    81b6781d-4224-4093-a577-480f15545861: Slogan # Slogan
    81bec3ca-8e95-4530-b7a6-75bc23a56604: Contact # Contact
    83f2c17a-02dc-452e-8f88-9a24d342fa4e: 'Incorrect Logo Usage' # Incorrect Logo Usage
    98c2bfe5-6e45-4f37-8c99-e319f1a88af1: Logos # Logos
    231de198-3683-4015-b299-f40a845715bd: Partners # Partners
    402e0153-4328-4d36-89a4-f12deb063b01: 'SEO Settings' # SEO Settings
    416a86cd-8066-4c2e-8add-e32a69a0b3b9: 'TruckersMP ID' # TruckersMP ID
    480f7c1b-cf61-408a-bd58-9cf1741fb7ad: 'Instagram Username' # Instagram Username
    611a4f85-a52f-4a80-8c72-a08f043b4268: Summary # Summary
    641a4c89-68e5-4d42-a403-94c4e5607f4c: 'Press Kit URL' # Press Kit URL
    665ef879-9eb6-4341-9bde-0fa85e06f7cb: 'Blog Index' # Blog Index
    706c4c9e-4c90-418d-926e-9e26151b71e4: 'Example Description' # Example Description
    759acc15-f189-482d-af8b-3b8eb87ddd66: 'Correct Logo Usage' # Correct Logo Usage
    782ec44e-152d-4eda-9c77-e07ca1fecd99: Contact # Contact
    833dd4dc-ac2c-4413-b32f-76f0b12d02c4: 'Brand Guidelines' # Brand Guidelines
    917f5627-3dc6-423b-aa1d-d3e9d2553add: 'Member Rules' # Member Rules
    3238e03c-bb36-4104-99b4-49ba379e23ca: 'Global Fields' # Global Fields
    5307bdd9-65c1-4010-8063-0082b5513429: Position # Position
    7386afed-ad3a-4215-9779-22c0947e4b3e: 'Team Member Fields' # Team Member Fields
    7509bb77-4792-44c9-8aff-5b1f0d0bbee7: Apply # Apply
    9413c31d-3095-4413-a3a9-7aab05f22886: 'Community Rules' # Community Rules
    31015d93-cb7d-4480-b97e-929ad3938a7d: Partners # Partners
    38928dc1-8714-4f7a-97bd-d3d445732573: 'Steam Group' # Steam Group
    47331c11-260a-426b-9818-ae9c5211bacc: Press # Press
    121970e2-9425-45cd-a8f1-7f026e67839e: Socials # Socials
    707026a3-1953-4b64-a6fb-f842bdfafde7: News # News
    17745760-d15d-404c-8007-88aa827c733d: Logo # Logo
    20481930-71dd-40a8-95d9-706aebeb215a: 'Twitch Username' # Twitch Username
    33577458-f61e-48ff-975b-66e9b15f8fe1: 'Terms and Conditions' # Terms and Conditions
    95971943-f483-45a2-9c05-c74ea1ef6475: 'Terms and Conditions' # Terms and Conditions
    a188b6b7-e2cc-4ded-863e-b4cf8007ea57: 'Privacy Policy' # Privacy Policy
    a572aba4-62e9-4bf7-a5c7-d98c59ae4c3a: 'Steam ID' # Steam ID
    ac16972b-cbc7-4985-ba76-0bdc2d397b5b: Apply # Apply
    ad11b19f-af61-4b8a-b6e0-330e0f66a7bb: Email # Email
    ae17d579-95d6-4196-a49d-d3fe6c4a3c1b: 'Job Title' # Job Title
    aecaf734-f36e-4662-bb30-795eaa9300ed: 'Cookie Policy' # Cookie Policy
    b0777c01-9f29-4b74-a410-1c07259d96ec: 'GitHub Username' # GitHub Username
    b6aabefd-345d-4c38-a13a-caf0636d73ca: 'Team Positions' # Team Positions
    b6223c95-f24b-47d0-85a1-21d91382e1bf: Press # Press
    b415578a-cf2b-4b20-8324-b17eed10e0e5: Brand # Brand
    ba185bf2-d6ec-4a15-898e-f2bb827f9e67: 'Our Fleet' # Our Fleet
    bdf8d171-13f4-464d-9eb6-58ef078c2118: Example # Example
    bee2519e-ac80-4425-a6b0-8cdbb8e094d4: 'Team Index' # Team Index
    bfb6dafa-b0e3-4838-a9d9-b73b1b958087: 'Terms and Conditions' # Terms and Conditions
    c1b4fdeb-34af-4ec3-afb6-b5f30a2a2fa5: 'Privacy Policy' # Privacy Policy
    c1bf131e-1a72-4499-89c3-deaeefc77929: Press # Press
    c29d58b1-7ac7-481c-b814-fa6bb8898a37: Default # Default
    c48b8408-ca02-4d29-986e-31a35a7dab20: 'Cookie Policy' # Cookie Policy
    c681a19b-210e-4008-9b67-9ce6bc045c47: 'TruckersMP VTC ID' # TruckersMP VTC ID
    c3004940-6ea1-4bd4-845f-9dbef81fa243: 'Brand Book URL' # Brand Book URL
    c8389542-b6fa-4246-b78a-2fc2e1264ece: About # About
    ca553da7-62b5-4f20-a874-5d7d846cb931: Team # Team
    d81fe9c4-26c1-4f72-8c78-89894a2ae2f4: 'Post Fields' # Post Fields
    d804ee0f-dda6-44c6-945a-43844a425f57: 'In Progress' # In Progress
    d524426a-5fd4-43af-a635-1ccbbe09875b: Examples # Examples
    dc6e9949-7832-497f-8453-c4982c626a9c: Partners # Partners
    dcd87449-f024-484e-b16d-21f3a078647e: 'Company Socials' # Company Socials
    de5d5736-6132-4731-a93d-e5a74d0d6b36: Blog # Blog
    de587533-76d9-4747-a138-71e89ccee6f5: Site # Site
    e8cf3d59-dc7d-4d37-9c21-e03049533db0: Rules # Rules
    e21f420c-3fc2-4ddc-afdc-b4ae78c526e3: Author # Author
    e50e2ae1-1c46-4cc3-922a-8b9568186243: Legal # Legal
    e9813ba6-2bb3-44d9-86aa-4e478bd1c82d: 'Our DriversHub' # Our DriversHub
    e1703234-d6af-4b85-9cd4-6b0b7c35b7fe: 'News Index' # News Index
    ea97fd7b-0a78-47d9-b148-9ef9056d44a0: Website # Website
    ebc67018-3219-40f0-b490-cbad36b6f924: Phoenix # Phoenix
    eda59c5d-c991-453a-93a9-c4db97859fdb: 'Blog Index' # Blog Index
    ef7d02b7-56f0-4b22-b9ef-1c9f4e351569: 'Twitter Username' # Twitter Username
    f2cf9586-f81f-404f-b8e6-57b9fe1d530d: 'Post Categories' # Post Categories
    f4c60350-d227-470d-8a13-7a70782c8d64: 'Site Information' # Site Information
    f8d2fcf0-a54c-4729-854b-11f93c2ae7a8: Blog # Blog
    f191a082-28aa-4279-8d57-3f94faa7645d: 'Brand Colours' # Brand Colours
    f769ee18-1b99-4a77-ac43-171d9805aa76: 'Site Description' # Site Description
    f4479ce4-5eda-4b2a-90e7-63c5bf0b14a4: Colours # Colours
    f2688023-802e-4b37-b142-63bff5102c1f: Description # Description
    fc020470-86c3-46e1-9bca-440954ee7bf6: Rules # Rules
    ff836a93-5b57-4613-8ff8-f2a28e86ff77: Press # Press
plugins:
  assetrev:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  blitz:
    edition: standard
    enabled: true
    licenseKey: R26T0LGW4I38NZFHMDOSVA0G
    schemaVersion: 3.10.0
    settings:
      apiKey: ''
      cacheControlHeader: 'public, s-maxage=31536000, max-age=0'
      cacheDuration: null
      cacheElementQueries: true
      cacheElements: true
      cachePurgerSettings:
        __assoc__:
          -
            - zoneIds
            -
              __assoc__:
                -
                  - 0a9ef065-97f8-4583-b4a1-5a8e4d790203 # Phoenix
                  -
                    __assoc__:
                      -
                        - zoneId
                        - 62311f4a569d9453da33311ad1afd523
          -
            - authenticationMethod
            - apiToken
          -
            - apiToken
            - $CLOUDFLARE_API_TOKEN
          -
            - apiKey
            - ''
          -
            - email
            - ''
          -
            - warmCacheDelay
            - '0'
      cachePurgerType: putyourlightson\blitz\drivers\purgers\CloudflarePurger
      cacheStorageSettings:
        __assoc__:
          -
            - folderPath
            - '@webroot/cache/blitz'
          -
            - createGzipFiles
            - '1'
          -
            - createBrotliFiles
            - ''
      cacheStorageType: putyourlightson\blitz\drivers\storage\FileStorage
      cacheWarmerSettings:
        __assoc__:
          -
            - concurrency
            - '3'
      cacheWarmerType: putyourlightson\blitz\drivers\warmers\GuzzleWarmer
      cachingEnabled: ''
      clearCacheAutomatically: '1'
      customSiteUris: ''
      debug: false
      deployerType: putyourlightson\blitz\drivers\deployers\DummyDeployer
      driverJobPriority: 100
      excludedQueryStringParams:
        - gclid
        - fbclid
      excludedUriPatterns:
        1:
          __assoc__:
            -
              - uriPattern
              - /contact
        2:
          __assoc__:
            -
              - uriPattern
              - /press
      includedQueryStringParams:
        - '.*'
      includedUriPatterns:
        -
          __assoc__:
            -
              - uriPattern
              - '.*'
      injectScriptEvent: DOMContentLoaded
      integrations:
        - putyourlightson\blitz\drivers\integrations\FeedMeIntegration
        - putyourlightson\blitz\drivers\integrations\SeomaticIntegration
      maxRetryAttempts: 10
      mutexTimeout: 1
      outputComments: true
      queryStringCaching: '1'
      queueJobTtr: 300
      refreshCacheAutomaticallyForGlobals: true
      refreshCacheJobPriority: 10
      refreshCacheWhenElementSavedNotLive: false
      refreshCacheWhenElementSavedUnchanged: false
      sendPoweredByHeader: true
      warmCacheAutomatically: '1'
      warmPagesWithQueryStringParams: true
  blitz-recommendations:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cookie-consent:
    edition: standard
    enabled: true
    licenseKey: MOW4MYYEDJW7JLMR4VWR9R5Q
    schemaVersion: 1.5.0
  craft-color-mixer:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  eager-beaver:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  element-relations:
    edition: standard
    enabled: true
    licenseKey: J4MMSAA5V8DHJ6BHMY6VDUM2
    schemaVersion: 1.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      expandSingles: '1'
      redirectToEntry: '1'
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 4.4.0
  fetch:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: HQQCLQJN56WBSMUBD076DO0B
    schemaVersion: 1.2.6
    settings:
      ajaxTimeout: '10'
      alertEmails: null
      captchas:
        __assoc__:
          -
            - recaptcha
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Recaptcha
                -
                  - enabled
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - recaptcha
                      -
                        - secretKey
                        - $RECAPTCHA_SECRET_KEY
                      -
                        - siteKey
                        - $RECAPTCHA_SITE_KEY
                      -
                        - type
                        - v3
                      -
                        - size
                        - normal
                      -
                        - theme
                        - light
                      -
                        - badge
                        - bottomleft
                      -
                        - language
                        - en
                      -
                        - minScore
                        - '0.5'
          -
            - duplicate
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Duplicate
                -
                  - enabled
                  - false
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - duplicate
          -
            - honeypot
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Honeypot
                -
                  - enabled
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - honeypot
          -
            - javascript
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Javascript
                -
                  - enabled
                  - false
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - javascript
                      -
                        - minTime
                        - ''
      defaultDateDisplayType: ''
      defaultDateTime: null
      defaultDateValueOption: ''
      defaultEmailTemplate: ''
      defaultFileUploadVolume: ''
      defaultFormTemplate: ''
      defaultInstructionsPosition: verbb\formie\positions\AboveInput
      defaultLabelPosition: verbb\formie\positions\AboveInput
      defaultPage: submissions
      enableCsrfValidationForGuests: true
      enableGatsbyCompatibility: false
      enableUnloadWarning: ''
      maxIncompleteSubmissionAge: 30
      maxSentNotificationsAge: 30
      pluginName: Forms
      saveSpam: true
      sendEmailAlerts: false
      sentNotifications: true
      spamBehaviour: showSuccess
      spamBehaviourMessage: ''
      spamEmailNotifications: false
      spamKeywords: ''
      spamLimit: 500
      useQueueForIntegrations: true
      useQueueForNotifications: true
  imager-x:
    edition: pro
    enabled: true
    licenseKey: 1F7TBF6XNRHVC2VZQWSQM5IC
    schemaVersion: 3.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  plausible:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      apiKey: $PLAUSIBLE_API_KEY
      siteId: $PLAUSIBLE_SITE_ID
  read-time:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  retour:
    edition: standard
    enabled: true
    licenseKey: UB2NEYH2YHP8SC2Y2U46IGRJ
    schemaVersion: 3.0.10
  seomatic:
    edition: standard
    enabled: true
    licenseKey: GR1TWPN4PCDBBOYOEZOCJK37
    schemaVersion: 3.0.11
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      alwaysIncludeCanonicalUrls: true
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: false
      enableMetaContainerEndpoint: false
      enableSeoFileLinkEndpoint: false
      environment: live
      excludeNonCanonicalUrls: false
      generatorEnabled: false
      headersEnabled: true
      includeHomepageInBreadcrumbs: true
      lowercaseCanonicalUrl: true
      manuallySetEnvironment: false
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 'null'
      pluginName: SEO
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
        - discord
      siteGroupsSeparate: '1'
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
      truncateDescriptionTags: '1'
      truncateTitleTags: '1'
  squeeze:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  trending-posts:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: Phoenix
  retryDuration: null
  schemaVersion: 3.7.8
  timeZone: Europe/London
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
