fieldLayouts:
  25d39a14-9c8a-498a-a78f-b062c2413726:
    tabs:
      -
        elements:
          -
            fieldUid: 1ee3f36f-8538-47a1-8ed5-6f0e6986693f # FAQ Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Frequently Asked Questions'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 2c156369-c025-4b90-86b7-878137ad5113 # Requirements
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Requirements
        sortOrder: 2
handle: recruitment
name: Recruitment
sortOrder: 1
