fieldLayouts:
  19de3b9b-1636-486a-9282-66d34909c845:
    tabs:
      -
        elements:
          -
            fieldUid: 9413c31d-3095-4413-a3a9-7aab05f22886 # Community Rules
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Community Rules'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 917f5627-3dc6-423b-aa1d-d3e9d2553add # Member Rules
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Member Rules'
        sortOrder: 2
handle: ruleset
name: Rules
sortOrder: 2
