defaultPlacement: end
enableVersioning: false
handle: careersIndex
name: 'Careers Index'
propagationMethod: all
siteSettings:
  0a9ef065-97f8-4583-b4a1-5a8e4d790203: # Phoenix
    enabledByDefault: true
    hasUrls: true
    template: careers/index
    uriFormat: careers
type: single
