defaultPlacement: end
enableVersioning: true
handle: cookiePolicy
name: 'Cookie Policy'
propagationMethod: all
siteSettings:
  0a9ef065-97f8-4583-b4a1-5a8e4d790203: # Phoenix
    enabledByDefault: true
    hasUrls: true
    template: legal/cookie-policy
    uriFormat: cookie-policy
type: single
