defaultPlacement: end
enableVersioning: true
handle: ourDrivershub
name: 'Our DriversHub'
propagationMethod: all
siteSettings:
  0a9ef065-97f8-4583-b4a1-5a8e4d790203: # Phoenix
    enabledByDefault: true
    hasUrls: true
    template: about-us\drivershub
    uriFormat: about-us/drivershub
type: single
