defaultPlacement: end
enableVersioning: true
handle: ourFleet
name: 'Our Fleet'
propagationMethod: all
siteSettings:
  0a9ef065-97f8-4583-b4a1-5a8e4d790203: # Phoenix
    enabledByDefault: true
    hasUrls: true
    template: about-us\our-fleet
    uriFormat: about-us/our-fleet
type: single
