defaultPlacement: end
enableVersioning: true
handle: partners
name: Partners
propagationMethod: all
siteSettings:
  0a9ef065-97f8-4583-b4a1-5a8e4d790203: # Phoenix
    enabledByDefault: false
    hasUrls: false
    template: null
    uriFormat: null
type: channel
