defaultPlacement: end
enableVersioning: true
handle: press
name: Press
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0a9ef065-97f8-4583-b4a1-5a8e4d790203: # Phoenix
    enabledByDefault: true
    hasUrls: true
    template: press/_entry
    uriFormat: press
type: single
