defaultPlacement: end
enableVersioning: true
handle: termsAndConditions
name: 'Terms and Conditions'
propagationMethod: all
siteSettings:
  0a9ef065-97f8-4583-b4a1-5a8e4d790203: # Phoenix
    enabledByDefault: true
    hasUrls: true
    template: legal\terms-and-conditions
    uriFormat: terms-and-conditions
type: single
