defaultPlacement: end
enableVersioning: true
handle: timeline
name: Timeline
propagationMethod: all
siteSettings:
  0a9ef065-97f8-4583-b4a1-5a8e4d790203: # Phoenix
    enabledByDefault: false
    hasUrls: true
    template: timeline/_entry
    uriFormat: 'timeline/{slug}'
type: channel
